### ISSUE TITLE
Parse DMS string without comma

### ISSUE THREAD

**Issue by rayshan** [Turistforeningen/dms2dec.js#1]
Hi, thanks for this. Please consider the output of https://github.com/dberesford/exiv2node:

``` json
{
    "Exif.GPSInfo.GPSAltitude": "51104/165",
    "Exif.GPSInfo.GPSAltitudeRef": "0",
    "Exif.GPSInfo.GPSDateStamp": "2012:08:31",
    "Exif.GPSInfo.GPSImgDirection": "53226/149",
    "Exif.GPSInfo.GPSImgDirectionRef": "T",
    "Exif.GPSInfo.GPSLatitude": "44/1 5633/100 0/1",
    "Exif.GPSInfo.GPSLatitudeRef": "N",
    "Exif.GPSInfo.GPSLongitude": "93/1 1916/100 0/1",
    "Exif.GPSInfo.GPSLongitudeRef": "W",
    "Exif.GPSInfo.GPSTimeStamp": "23/1 47/1 13970/1000",
}
```

`"44/1 5633/100 0/1"` will not be parsed. A workaround is to do `"44/1 5633/100 0/1".split(" ")`. Since you already consider so many formats, it'll be nice if this is considered too.

**Comment by Starefossen** [comment]
Thanks for the heads up about `exiv2node`. I think it should be fairly easy to add support this format as well 😄

**Comment by Starefossen** [comment]
`dms2dec@1.1.0` is now available from npm with support for dms strings without comas. Thanks for suggesting this improvement @rayshan!

**Comment by rayshan** [comment]
:tada: that was quick, you rock!
